const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const AUTHENTICATE = "AUTHENTICATE";
const GET_INITIAL_DATA = "GET_INITIAL_DATA";
const SET_LOADING = "SET_LOADING";
const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";
const FETCH_TRAILER_START="FETCH_TRAILER_START";
const FETCH_TRAILER_SUCCESS="FETCH_TRAILER_SUCCESS";
const FETCH_TRAILER_ERROR="FETCH_TRAILER_ERROR";

export {
  LOG_IN,
  LOG_OUT,
  AUTHENTICATE,
  GET_INITIAL_DATA,
  SET_LOADING,
  OPEN_MODAL,
  CLOSE_MODAL,
  FETCH_TRAILER_ERROR,
  FETCH_TRAILER_START,
  FETCH_TRAILER_SUCCESS

};
