const GET_INITIAL_POSTS = "GET_INITIAL_POSTS";
const REMOVE_POST = "REMOVE_POST";
const SET_LOADING = "SET_LOADING";
const SET_ERROR = "SET_ERROR";
const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";
const SET_LOGIN_STATUS ='SET_LOGIN_STATUS'
export {
  GET_INITIAL_POSTS,
  REMOVE_POST,
  SET_LOADING,
  SET_ERROR,
  OPEN_MODAL,
  CLOSE_MODAL,
  SET_LOGIN_STATUS
};
