const GET_INITIAL_POSTS ='GET_INITIAL_POSTS'
const SET_LOGIN_STATUS ='SET_LOGIN_STATUS'
const SET_LOADING = "SET_LOADING";
const SET_ERROR = "SET_ERROR";
const SET_PAGE ='SET_PAGE'
const ADD_TO_CART ='ADD_TO_CART'
const REMOVE_FROM_CART ='REMOVE_FROM_CART'
export{
    GET_INITIAL_POSTS,
    SET_LOGIN_STATUS,
    SET_ERROR,
    SET_LOADING,
    SET_PAGE,
    ADD_TO_CART,
    REMOVE_FROM_CART

}